### ISSUE TITLE
Is MySQL an option?

### ISSUE THREAD

**Issue by s22-tech** [giventofly/teikirize-bookmarks#1]
Am I reading this right?  Is this for SQLite only, or can this script also be run from MySQL?  

Hopefully it's both.  It looks pretty nice, but my server only has MySQL.  Thanks!

**Comment by giventofly** [comment]
Hi,

it is supposed to be used with sqlite so you wouldn't be needing to install mysql and work with just php running.

You can change it to work with mysql, but don't you have the module for SQLite or just don't want to use it ?

**Comment by s22-tech** [comment]
SQLite is not available on this server, so I have to use MySQL or MariaDB.

**Comment by giventofly** [comment]
Just to be clear, sqlite is just a file that php reads using a php extension https://www.php.net/manual/en/book.sqlite3.php

All the servers that I used all had support for sqlite3, are you sure you don't have it? can you check with phpinfo ?

**Comment by s22-tech** [comment]
You were correct — it was there.  I guess I was working off old information.

I got it installed and it looks pretty nice so far.  I like the small footprint.  Thanks!

**Comment by giventofly** [comment]
Glad everything worked out! :)
